const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),pub=path.join(root,'public');
const guidedCounts=[5,5,4,4,5,5,4,4,4,4,5,4,4,5,4,4];
const units=guidedCounts.map((_,i)=>({id:i+1,title:`Unit ${i+1}`})),lessons=[];
for(let u=1;u<=16;u++)for(let i=1;i<=guidedCounts[u-1];i++)lessons.push({id:`u${u}-lesson-${i}`,unit:u,title:`Unit ${u} Lesson ${i}`,reading:'Genesis 1:1–5',ref:[1,1,1,5]});
const D={units,lessons},context={window:{FOUNDATIONS_DATA:D},console};vm.createContext(context);
for(const file of ['foundations-skill-source.js','foundations-skill-curriculum.js'])vm.runInContext(fs.readFileSync(path.join(pub,file),'utf8'),context,{filename:file});
assert.equal(D.lessons.length,70);assert.equal(D.skillMissions.length,69);assert.equal(D.integratedCurriculum.totalActivities,139);assert.equal(D.integratedCurriculum.units,16);assert.equal(new Set(D.skillMissions.map(m=>m.id)).size,69);
assert.deepEqual(Array.from(D.skillTracks,t=>[t.id,t.steps]),[['story',10],['order',17],['groups',12],['chrono',7],['content',8],['themes',7],['verses',8]]);assert.equal(D.integratedCurriculum.model,'one-curriculum');assert.equal(D.integratedCurriculum.skillMissions,69);
for(const m of D.skillMissions){assert.ok(m.lessonId);assert.ok(m.unit>=1&&m.unit<=16);assert.equal(m.body.length,4);assert.equal(Object.keys(m.vocab).length,3);assert.ok(m.objective&&m.simple&&m.deeper&&m.reflect&&m.model);assert.ok(m.originalCheck&&Object.keys(m.originalCheck).length)}
const assigned=D.lessons.flatMap(l=>l.skillMissions||[]);assert.equal(assigned.length,69);assert.equal(new Set(assigned).size,69);
const expectedUnitMissionCounts=[4,4,4,4,6,4,5,4,4,4,3,3,4,3,6,7],actualUnitMissionCounts=units.map(u=>D.skillMissions.filter(m=>m.unit===u.id).length);assert.deepEqual(actualUnitMissionCounts,expectedUnitMissionCounts);for(const [i,count] of actualUnitMissionCounts.entries()){assert.ok(count>=3&&count<=7);const perLesson=D.lessons.filter(l=>l.unit===i+1).map(l=>(l.skillMissions||[]).length);assert.ok(Math.max(...perLesson)<=2)}
const expectedLegacyIds=['s.1','s.2','s.3','s.4','s.5','s.6','s.7','s.8','s.9','s.10','o.law','o.hist1','o.hist2','o.hist3','o.wisdom','o.major','o.minor1','o.minor2','o.minor3','o.ot','o.gospels','o.paul1','o.paul2','o.paul3','o.general','o.nt','o.all','g.map','g.law','g.hist','g.wis','g.major','g.minor','g.gospel','g.paul','g.gen','g.proph','g.edges','g.all','c.two','c.eras','c.anchor','c.oop','c.proph','c.paul','c.all','n.what','n.nt','n.plot','n.people1','n.people2','n.author','n.audience','n.all','t.what','t.cov','t.exile','t.sac','t.mercy','t.faith','t.all','v.what','v.proph','v.love','v.strength','v.fruit','v.speaker','v.build','v.all'];assert.deepEqual(Array.from(D.skillMissions,m=>m.legacyId),expectedLegacyIds);
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');for(const file of ['foundations-expansion-core.js','foundations-units-02-08.js','foundations-units-09-16.js','foundations-skill-source.js','foundations-skill-curriculum.js','foundations-expansion-meta.js','foundations-expansion-finalize.js'])assert.ok(loader.includes(file));assert.ok(loader.indexOf('foundations-skill-source.js')<loader.indexOf('foundations-skill-curriculum.js')&&loader.indexOf('foundations-skill-curriculum.js')<loader.indexOf('foundations-expansion-meta.js'));assert.ok(loader.includes('v5-shell.css')&&loader.includes('v5-shell.js'),'v5 shell must load after the stable curriculum runtime');
const worker=fs.readFileSync(path.join(root,'worker.js'),'utf8');assert.ok(!worker.includes('HTMLRewriter'));assert.ok(worker.includes('env.ASSETS.fetch'));
const finalizer=fs.readFileSync(path.join(pub,'foundations-expansion-finalize.js'),'utf8');assert.ok(finalizer.includes('139 learning activities'));assert.ok(finalizer.includes('data-skill-mission'));assert.ok(!finalizer.includes('data-skill-track="'));assert.ok(!finalizer.includes('S.legacyLearn'));
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');assert.ok(sw.includes('canon-v5-experience-1'));assert.ok(sw.includes('foundations-expansion-loader.js'));assert.ok(sw.includes('foundations-skill-source.js')&&sw.includes('foundations-skill-curriculum.js'));
console.log('PASS: 16-unit source curriculum feeds the preserved 70 guided + 69 mastery activity model beneath v5');
