const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const visuals=fs.readFileSync(path.join(pub,'v4-visuals.js'),'utf8');
const gamesCode=fs.readFileSync(path.join(pub,'v4-games.js'),'utf8');
for(const type of ['timeline','flow','compare','shelf','story-arc','relationship','theme-thread','verse-context','book-profile','spectrum','stack','map-lite'])assert.ok(visuals.includes(type),`visual renderer missing ${type}`);
for(const type of ['timeline-sort','sequence-path','match-board','evidence-lab','context-lens','argument-map','compare-board','scenario','verse-rebuild','book-detective','theme-trace','capstone'])assert.ok(gamesCode.includes(type),`game renderer missing ${type}`);
assert.ok(gamesCode.includes('aria-labelledby="v4-game-title"'),'game region needs an accessible heading relationship');
assert.ok(gamesCode.includes('data-game-feedback'),'feedback needs a stable focus target');
assert.ok(gamesCode.includes('role="progressbar"'),'challenge progress needs progress semantics');
const ctx={window:{},console,JSON,Math};vm.createContext(ctx);vm.runInContext(gamesCode,ctx,{filename:'v4-games.js'});const G=ctx.window.CanonV4Games;
const noHint=G.init({kind:'capstone',title:'Pick one',options:['A','B'],answer:0,clues:['x']});assert.ok(!G.render(noHint).includes('data-game-action="hint"'),'hint control should not render without hint content');
const locked=G.init({kind:'capstone',title:'Pick one',options:['A','B'],answer:0,clues:['x'],hints:['Read the clue.'],why:'Correct.'});G.act(locked,'single',{i:'0'});G.act(locked,'check',{});assert.equal(locked.state.correct,true);assert.ok(G.render(locked).includes('data-game-action="next"'));assert.ok(!G.render(locked).includes('data-game-action="check"'));G.act(locked,'single',{i:'1'});assert.deepEqual(locked.state.selected,[0],'a completed answer must be frozen against accidental mutation');
assert.ok(G.render(locked).includes('disabled'),'completed answer controls should visibly disable');
assert.ok(gamesCode.includes('prefers-reduced-motion')||fs.readFileSync(path.join(pub,'v4-design-system.css'),'utf8').includes('prefers-reduced-motion'),'reduced-motion support missing');
console.log('PASS v4 visual/game renderer coverage, completion locking, hints, and accessibility semantics');
