const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const md=fs.readFileSync(path.join(pub,'statement-of-faith.md'),'utf8');
const js=fs.readFileSync(path.join(pub,'v5-faith.js'),'utf8');
const css=fs.readFileSync(path.join(pub,'v5-pages.css'),'utf8');
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
assert.equal((md.match(/^## Article /gm)||[]).length,19,'Statement of Faith must contain all nineteen articles');
for(const phrase of ['Jesus is the lens through which Scripture is rightly read','Grace is not heterosexuality. The gospel is not heterosexuality. The gospel is Jesus Christ.','People seeking Christ deserve shepherds, not prosecutors.','Belonging precedes certainty','Prayer is relationship, not leverage.','Intellectual humility is a Christian virtue.'])assert.ok(md.includes(phrase),`missing core statement language: ${phrase}`);
assert.ok(md.includes('Article XI — Of Sexuality, Relationships, and Inclusion')&&md.includes('LGBTQ+ Christians may follow Jesus, worship, serve, lead, form families, enter committed relationships and marriages'),'affirming article must be preserved');
assert.ok(md.includes('Article XIX — Of the Application and Amendment of This Statement')&&md.includes('not required to affirm this Statement'),'institutional application clause missing');
assert.ok(!md.includes('Marketing analytics')&&!md.includes('isolated-segment')&&!md.includes('\nsvg\n'),'export artifacts must not enter the published statement');
assert.ok(js.includes("fetch(new URL('statement-of-faith.md',base))")&&js.includes('v5-faith-v3'),'v5 must render the canonical statement source');
assert.ok(css.includes('.v5-faith-v3')&&css.includes('.v5-faith-version'),'Statement of Faith needs dedicated long-form editorial styling');
assert.ok(loader.indexOf('v5-faith.js')>loader.indexOf('v5-pages.js'),'faith renderer must load after the v5 application layer');
assert.ok(sw.includes('canon-v5-experience-3')&&sw.includes('./v5-faith.js')&&sw.includes('./statement-of-faith.md'),'Statement of Faith must be available offline');
console.log('PASS v5 faith: full 19-article TopherLoring Ministries Statement of Faith is published, styled, and cached offline');
