const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const js=fs.readFileSync(path.join(pub,'v5-mobile-bible.js'),'utf8');
const css=fs.readFileSync(path.join(pub,'v5-mobile-bible.css'),'utf8');
const data=fs.readFileSync(path.join(pub,'v5-book-study-data.js'),'utf8');
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
new Function(js);new Function(data);
assert.ok(css.includes('--app-gutter')&&css.includes('env(safe-area-inset-left)')&&css.includes('@media(max-width:700px)'),'mobile layout must use explicit gutters, safe areas, and a phone breakpoint');
assert.ok(css.includes('grid-template-columns:repeat(5,minmax(0,1fr))'),'all five primary destinations must fit intentionally on phone');
assert.ok(css.includes('.v5-book-study')&&css.includes('.v5-spine-name'),'Bible profiles and readable spine names need dedicated styling');
assert.ok(css.includes('.v5-retired-learned{display:none!important}'),'Mark as learned must be retired from book details');
assert.ok(css.includes('scroll-padding-top:var(--app-header-offset)')&&css.includes('scroll-margin-top:var(--app-header-offset)'),'sticky header must not obscure navigated Bible content');
assert.ok(js.includes("'Genesis','Exodus'")&&js.includes("'Jude','Revelation'"),'book enhancement must cover the full Protestant shelf');
for(const phrase of ['Key themes','Go deeper','Common questions','Where readers differ','Translation & textual notes','Common ground'])assert.ok(js.includes(phrase),`book profile layer missing ${phrase}`);
assert.ok(js.includes('mark\\s+(?:this\\s+)?(?:book\\s+)?as\\s+learned'),'book detail cleanup must explicitly retire Mark as learned');
assert.ok(js.includes('syncAfterChapterNav')&&js.includes('previous|next'),'chapter navigation must resync the study/book state');
assert.ok(js.includes('scrubVersionCopy')&&js.includes('updateAboutToolCopy'),'learner-facing implementation/version language must be cleaned up');
assert.ok(data.includes('window.CANON_BOOK_STUDY')&&data.includes('Genesis')&&data.includes('Matthew')&&data.includes('Revelation'),'study data must span both testaments');
assert.ok(data.includes('Comma Johanneum')&&data.includes('Isaiah 7:14')&&data.includes('earliest surviving manuscripts end at 16:8'),'translation/textual notes must include concrete examples where material');
assert.ok(loader.indexOf('v5-mobile-bible.js')>loader.indexOf('v5-pages.js')&&loader.includes('v5-book-study-data.js'),'enhancement layer must load after page architecture');
for(const asset of ['./v5-mobile-bible.css','./v5-book-study-data.js','./v5-mobile-bible.js'])assert.ok(sw.includes(asset),`${asset} must work offline`);
console.log('PASS mobile/Bible: phone-first gutters/nav, Bible shelf/profile enrichment, chapter sync, dense search styling, and version-copy cleanup are wired');
