const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const pages=fs.readFileSync(path.join(pub,'v5-pages.js'),'utf8');
const css=fs.readFileSync(path.join(pub,'v5-pages.css'),'utf8');
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
assert.ok(pages.includes('window.CANON_V4_COURSE'),'Course page must use the authoritative 25-unit map');
assert.ok(pages.includes('data-v5-unit'),'Course needs visible unit navigation');
for(const label of ['Bookshelf','Books & groups','Bible reader','Canon & timeline'])assert.ok(pages.includes(label),`Bible tool missing ${label}`);
assert.ok(pages.includes("if(shelf&&bible&&!bible.contains(shelf))"),'bookshelf must be audited back into Bible');
for(const label of ['Ask / search','Theology & doctrine','Christian life','Biblical concepts','Difficult questions','Glossary','Related exploration'])assert.ok(pages.includes(label),`Topics architecture missing ${label}`);
for(const key of ['review','order','context','themes','verses','games'])assert.ok(pages.includes(`${key}:`)||pages.includes(`'${key}'`),`Practice action missing ${key}`);
assert.ok(pages.includes("input.placeholder='Search Scripture or site…'"),'global search must cover Scripture and site topics');
assert.ok(pages.includes("scripture=/^(?:[1-3]"),'global search must distinguish Scripture references');
assert.ok(pages.includes('v5-progress-dialog')&&pages.includes('Profile & progress'),'profile/progress dialog missing');
assert.ok(pages.includes('canon.v4.progress.1'),'v5 Home/Profile must reuse local v4 progress rather than invent a second store');
assert.ok(css.includes('.v5-unit-grid')&&css.includes('.v5-bible-tools')&&css.includes('.v5-topic-map')&&css.includes('.v5-practice-map'),'page-level design system incomplete');
assert.ok(css.includes('.v5-retired-masthead')&&css.includes('.v5-retired-tabbar'),'legacy top-level chrome must be visually retired');
assert.ok(css.includes('.v5-faith-v3'),'full Statement of Faith needs dedicated editorial styling');
assert.ok(css.includes('prefers-reduced-motion')&&css.includes('forced-colors'),'page-level accessibility fallbacks missing');
assert.ok(loader.indexOf('v5-pages.js')>loader.indexOf('v5-shell.js'),'page layer must mount after shell');
assert.ok(loader.indexOf('v5-faith.js')>loader.indexOf('v5-pages.js'),'faith layer must mount after page layer');
assert.ok(loader.includes('v5-pages.css'));
assert.ok(sw.includes('canon-v5-experience-3')&&sw.includes('./v5-pages.js')&&sw.includes('./v5-pages.css')&&sw.includes('./v5-faith.js')&&sw.includes('./statement-of-faith.md'));
console.log('PASS v5 pages: Course/Bible/Topics/Practice are first-class experiences, global search/profile enhanced, legacy chrome retired, full faith statement integrated');
