const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const pages=fs.readFileSync(path.join(pub,'v5-pages.js'),'utf8');
const css=fs.readFileSync(path.join(pub,'v5-pages.css'),'utf8');
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
new Function(pages);
assert.ok(pages.includes('window.CANON_V4_COURSE'),'Course page must use the authoritative 25-unit map');
assert.ok(pages.includes('data-v5-unit'),'Course needs visible unit navigation');
for(const label of ['Bookshelf','Books & groups','Bible reader','Canon & timeline'])assert.ok(pages.includes(label),`Bible tool missing ${label}`);
assert.ok(pages.includes("if(shelf&&bible&&!bible.contains(shelf))"),'bookshelf must be audited back into Bible');
for(const label of ['Ask / search','Theology & doctrine','Christian life','Biblical concepts','Difficult questions','Glossary','Related exploration'])assert.ok(pages.includes(label),`Topics architecture missing ${label}`);
for(const key of ['review','order','context','themes','verses','games'])assert.ok(pages.includes(`${key}:`)||pages.includes(`'${key}'`),`Practice action missing ${key}`);
assert.ok(pages.includes("input.placeholder='Search Scripture or site…'"),'global search must cover Scripture and site topics');
assert.ok(pages.includes("scripture=/^(?:[1-3]"),'global search must distinguish Scripture references');
assert.ok(pages.includes('v5-progress-dialog')&&pages.includes('Progress & backup'),'progress dialog missing');
assert.ok(pages.includes('canon.v4.progress.1'),'current Home/Profile must reuse the established local progress store rather than invent a second store');
assert.ok(pages.includes('v?.done'),'page progress must understand the authoritative done flag');
assert.ok(css.includes('.v5-unit-grid')&&css.includes('.v5-bible-tools')&&css.includes('.v5-topic-map')&&css.includes('.v5-practice-map'),'page-level design system incomplete');
assert.ok(css.includes('.v5-retired-masthead')&&css.includes('.v5-retired-tabbar'),'legacy top-level chrome must be visually retired');
assert.ok(css.includes('prefers-reduced-motion')&&css.includes('forced-colors'),'page-level accessibility fallbacks missing');
assert.ok(loader.indexOf('v5-pages.js')>loader.indexOf('v5-shell.js'),'page layer must mount after shell');
assert.ok(loader.indexOf('v5-mobile-bible.js')>loader.indexOf('v5-pages.js'),'mobile/Bible enhancement must mount after the page layer');
assert.ok(loader.indexOf('v5-progress-adapter.js')>loader.indexOf('v5-bible-continuity.js'),'progress adapter must mount after core v5 behavior');
assert.ok(loader.indexOf('v5-guided-tour.js')>loader.indexOf('v5-progress-adapter.js'),'guided tour must mount after learner-state enhancements');
assert.ok(loader.includes('v5-pages.css')&&loader.includes('v5-mobile-bible.css')&&loader.includes('v5-onboarding.css')&&loader.includes('v5-blueprint-r3.css'));
assert.ok(sw.includes('canon-v5-experience-6')&&sw.includes('./v5-pages.js')&&sw.includes('./v5-mobile-bible.js')&&sw.includes('./v5-inline-scripture.js')&&sw.includes('./v5-guided-tour.js')&&sw.includes('./v5-progress-adapter.js'));
console.log('PASS v5 pages: parse-safe Course/Bible/Topics/Practice with corrected progress contract');
