const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const shell=fs.readFileSync(path.join(pub,'v5-shell.js'),'utf8');
const css=fs.readFileSync(path.join(pub,'v5-shell.css'),'utf8');
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
for(const section of ['home','course','bible','topics','practice'])assert.ok(shell.includes(`data-v5-go=\\"${section}\\"`)||shell.includes(`data-v5-go="${section}"`),`missing primary destination ${section}`);
assert.ok(shell.includes('Statement of Faith'),'statement of faith must remain discoverable');
assert.ok(!/data-v5-go=[\\"]beliefs[\\"][^>]*>Beliefs</.test(shell),'beliefs must not become a primary navigation destination');
assert.ok(shell.includes("verse.hidden=true"),'legacy Verses tab should be retired from top-level navigation');
assert.ok(shell.includes("ex.textContent='Bible'"),'legacy Explore destination should be reframed as Bible');
assert.ok(shell.includes("$('.tabbar .search')||$('.search')"),'existing Bible search must be promoted into the global header');
assert.ok(css.includes('.v5-header')&&css.includes('backdrop-filter'),'v5 global header styling missing');
assert.ok(css.includes('prefers-reduced-motion')&&css.includes('forced-colors'),'motion and forced-color accessibility fallbacks missing');
assert.ok(shell.includes('document.startViewTransition'),'v5 should progressively enhance major route transitions');
assert.ok(loader.indexOf('v5-shell.js')>loader.indexOf('v4-shell-bridge.js'),'v5 must enhance the stable v4 shell last');
assert.ok(loader.includes('v5-shell.css'));
assert.ok(sw.includes('./v5-shell.js')&&sw.includes('./v5-shell.css'));
console.log('PASS v5 shell: five flat destinations, global utilities, footer beliefs, progressive motion, accessibility fallbacks');
