const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const pub=path.resolve(__dirname,'../public');
const shell=fs.readFileSync(path.join(pub,'v5-shell.js'),'utf8');
const css=fs.readFileSync(path.join(pub,'v5-shell.css'),'utf8');
const loader=fs.readFileSync(path.join(pub,'foundations-expansion-loader.js'),'utf8');
const sw=fs.readFileSync(path.join(pub,'sw.js'),'utf8');
for(const section of ['home','course','bible','topics','practice'])assert.ok(shell.includes(`data-v5-go=\"${section}\"`)||shell.includes(`data-v5-go="${section}"`),`missing primary destination ${section}`);
assert.ok(shell.includes("const ROUTES={course:{tab:'learn',panel:'panel-learn'},bible:{tab:'explore',panel:'panel-explore'},topics:{tab:'topics',panel:'panel-topics'},practice:{tab:'play',panel:'panel-play'}}"),'stable engines must be explicitly isolated behind v5 destinations');
assert.ok(shell.includes('function showOnly(route)'),'v5 routing must own visible panel state');
assert.ok(!shell.includes("allPanels().forEach(p=>p.hidden=false)"),'v5 must never expose all legacy panels together');
assert.ok(shell.includes("LEGACY_PANELS=['panel-play','panel-explore','panel-learn','panel-topics','panel-verses']"),'legacy panels must be treated as implementation surfaces, not parallel pages');
assert.ok(shell.includes('relocateShelf()')&&shell.includes("const bible=legacyPanel('panel-explore')"),'bookshelf must be relocated into Bible');
assert.ok(css.includes('.v5-bible-shelf')&&css.includes('body>.spine-block'),'bookshelf styling/isolation missing');
for(const retired of ['Learning map','Practice missions','Theology guide','Book drills'])assert.ok(shell.includes(`'${retired}'`),`legacy Practice control ${retired} must be retired from visible v5 UI`);
for(const practice of ['Recommended review','Book & order','Context & interpretation','Themes','Verses','Games & mastery'])assert.ok(shell.includes(practice),`Practice information architecture missing ${practice}`);
for(const home of ['Continue learning','Current progress','Suggested next activity','Explore Scripture','Featured topic','Recent activity'])assert.ok(shell.includes(home),`Home dashboard missing ${home}`);
for(const bible of ['Reader · bookshelf · canonical groups · book profiles · chapters · timeline'])assert.ok(shell.includes(bible),'Bible destination contract missing');
for(const topics of ['Theology · doctrine · Christian life · biblical concepts · difficult questions · glossary'])assert.ok(shell.includes(topics),'Topics destination contract missing');
for(const footer of ['Statement of Faith','About Canonical Shelf','How this guide approaches Scripture','Sources & methodology','Translation information','Accessibility','Privacy'])assert.ok(shell.includes(footer),`footer/about missing ${footer}`);
assert.ok(!/data-v5-go=[\\"]beliefs[\\"][^>]*>Beliefs</.test(shell),'beliefs must not become a primary navigation destination');
assert.ok(shell.includes("$('.tabbar .search')||$('.search')"),'existing Bible search must be promoted into the global header');
assert.ok(shell.includes('profileMarkup()')&&shell.includes('v5-profile-card'),'profile/progress control must exist in the global header');
assert.ok(css.includes('.v5-header')&&css.includes('backdrop-filter'),'v5 global header styling missing');
assert.ok(css.includes('prefers-reduced-motion')&&css.includes('forced-colors'),'motion and forced-color accessibility fallbacks missing');
assert.ok(shell.includes('document.startViewTransition'),'v5 should progressively enhance major route transitions');
assert.ok(loader.indexOf('v5-shell.js')>loader.indexOf('v4-shell-bridge.js'),'v5 must enhance the stable v4 shell last');
assert.ok(loader.includes('v5-shell.css'));
assert.ok(sw.includes('./v5-shell.js')&&sw.includes('./v5-shell.css'));
console.log('PASS v5 experience: flat destinations, isolated legacy engines, Bible-only shelf, redesigned Home/Practice, global utilities, footer/about');
